#!/usr/bin/env python3
"""
Regenerates the net8.0+ (Native AOT compatible) binding files from the
upstream reflection-based sources, so the fork stays mechanically in sync
with upstream when new librdkafka functions are added:

  Impl/NativeMethods/NativeMethods.cs      -> Impl/NativeMethods/NativeMethods.LibraryImport.cs
  Impl/NativeMethods/NativeMethods_*.cs    -> per-distro DllName constants / probe lists (same file)
  Impl/LibRdKafka.cs (SetDelegates(Type))  -> Impl/LibRdKafka.Modern.SetDelegates.cs
                                              (SetDelegates() + generated Adapters)

Run from the repository root:

  python3 scripts/gen-aot-bindings.py

Externs whose upstream signature cannot be expressed as a source-generated
P/Invoke (StringBuilder buffers, managed callback delegates) get a generated
adapter that keeps the upstream wrapper signature. A hand written adapter of
the same name in Impl/LibRdKafka.Modern.cs (used for the [UnmanagedCallersOnly]
callback trampolines) takes precedence and is skipped by the generator.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "src" / "Confluent.Kafka"
NATIVE_SRC = ROOT / "Impl" / "NativeMethods" / "NativeMethods.cs"
NATIVE_DST = ROOT / "Impl" / "NativeMethods" / "NativeMethods.LibraryImport.cs"
LIB_SRC = ROOT / "Impl" / "LibRdKafka.cs"
LIB_DST = ROOT / "Impl" / "LibRdKafka.Modern.SetDelegates.cs"
MODERN = ROOT / "Impl" / "LibRdKafka.Modern.cs"

GENERATED_BANNER = """// <auto-generated>
//     Generated by scripts/gen-aot-bindings.py from {src}.
//     Do not edit by hand - re-run the script after syncing with upstream.
// </auto-generated>
"""


def variant_dll_names() -> list:
    """(variant, DllName) for each upstream per-distro NativeMethods_<Variant>.cs."""
    variants = []
    for path in sorted(NATIVE_SRC.parent.glob("NativeMethods_*.cs")):
        variant = re.match(r"NativeMethods_(\w+)\.cs", path.name).group(1)
        # The last DllName const is the non-NET462 one (no .so suffix).
        name = re.findall(r'const string DllName = "([^"]+)";', path.read_text())[-1]
        variants.append((variant, name))
    return variants


def gen_native_methods() -> None:
    src = NATIVE_SRC.read_text()

    # Class documentation: the copy/paste rationale no longer applies.
    src = re.sub(
        r"    /// <summary>\n    ///     This class should be an exact replica.*?internal class NativeMethods\n",
        "    /// <summary>\n"
        "    ///     Source-generated (Native AOT compatible) P/Invoke declarations for\n"
        "    ///     librdkafka, used on net8.0 and later. The concrete native library\n"
        "    ///     (librdkafka / per-distro variant / user path) is selected by the\n"
        "    ///     DllImportResolver in LibRdKafka.Modern.cs.\n"
        "    /// </summary>\n"
        "    internal static unsafe partial class NativeMethods\n",
        src,
        flags=re.S,
    )

    src = src.replace("using System.Text;\n", "using System.Runtime.CompilerServices;\n")

    # CS3016: the CallConvs array argument is not CLS compliant; irrelevant
    # for an internal class but the assembly is marked [CLSCompliant].
    src = src.replace("\nnamespace Confluent.Kafka.Impl.NativeMethods\n",
                      "\n#pragma warning disable CS3016\n\nnamespace Confluent.Kafka.Impl.NativeMethods\n")

    # Per-distro variants. The DllImportResolver in LibRdKafka.Modern.cs probes
    # these lists, mirroring upstream's LoadLinuxDelegates: on Alpine the
    # variant(s) named after it, otherwise librdkafka first (GSSAPI linkage)
    # and then the remaining variants. Renaming or adding a variant upstream
    # is therefore picked up on regeneration; only a change to upstream's
    # selection *logic* needs a manual mirror in NativeLibraryCandidates().
    variants = variant_dll_names()
    consts = [f'        internal const string DllName_{v} = "{n}";' for v, n in variants]
    alpine = [n for v, n in variants if "alpine" in v.lower()] + ['librdkafka']
    linux = ['librdkafka'] + [n for v, n in variants if "alpine" not in v.lower()]
    lst = lambda names: ", ".join(f'"{n}"' for n in names)
    src = src.replace(
        '        public const string DllName = "librdkafka";\n',
        '        public const string DllName = "librdkafka";\n\n'
        "        // Per-distro variants, from upstream NativeMethods_*.cs.\n"
        + "\n".join(consts) + "\n\n"
        "        // Probe order used by the DllImportResolver (see LibRdKafka.Modern.cs).\n"
        f"        internal static readonly string[] AlpineDllNames = {{ {lst(alpine)} }};\n"
        f"        internal static readonly string[] LinuxDllNames = {{ {lst(linux)} }};\n")

    src = src.replace(
        "[DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]",
        "[LibraryImport(DllName, StringMarshalling = StringMarshalling.Utf8)]\n"
        "        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]",
    )

    # bool return values need an explicit marshaller; park them under a
    # placeholder so the bool *parameter* rewrite below leaves them alone.
    src = src.replace("static extern bool ", "static extern BOOLRET ")
    src = src.replace("static extern unsafe ", "static extern ")
    src = src.replace("static extern ", "static partial ")

    # StringBuilder is not supported by the generator (nor by AOT); generated
    # adapters bridge the upstream wrapper signatures.
    src = re.sub(r"StringBuilder (\w+)", r"byte* \1", src)

    # UTF-8 string marshalling is declared once on the attribute.
    src = re.sub(r"\[MarshalAs\(UnmanagedType\.LPStr\)\] ?", "", src)
    src = src.replace("[MarshalAs(UnmanagedType.LPArray)] string[]", "string[]")

    # Managed callback delegates are registered as raw function pointers.
    src = re.sub(r"Librdkafka\.\w+Delegate (\w+)", r"IntPtr \1", src)

    # bool parameters need an explicit marshaller.
    src = re.sub(r"(?<![\w.\]])bool (\w+)", r"[MarshalAs(UnmanagedType.Bool)] bool \1", src)

    src = re.sub(
        r"(\[UnmanagedCallConv[^\n]*\])\n(\s+)internal static partial BOOLRET ",
        r"\1\n\2[return: MarshalAs(UnmanagedType.Bool)]\n\2internal static partial bool ",
        src,
    )

    NATIVE_DST.write_text(GENERATED_BANNER.format(src=NATIVE_SRC.name) + src)


def parse_externs() -> dict:
    """
    name -> (return type, [(modifier, type, name)]) for every upstream extern,
    from the upstream (DllImport) declaration.
    """
    src = NATIVE_SRC.read_text()
    externs = {}
    # Whitespace and line comments may sit between the attribute and the declaration.
    for decl in re.findall(r"\[DllImport[^\]]*\](?:\s|//[^\n]*)*(internal static extern.*?;)", src, flags=re.S):
        decl = re.sub(r"//[^\n]*", "", decl)
        decl = re.sub(r"/\*.*?\*/", "", decl, flags=re.S)
        decl = re.sub(r"\[MarshalAs\([^)]*\)\]\s*", "", decl)
        decl = " ".join(decl.split())
        m = re.match(
            r"internal static extern (?:unsafe )?(?P<ret>[\w.<>\[\]*]+) (?P<name>rd_kafka_\w+)\s*\((?P<params>.*)\);$",
            decl,
        )
        if not m:
            sys.exit(f"cannot parse extern: {decl}")
        params = []
        for p in [p.strip() for p in m.group("params").split(",") if p.strip()]:
            parts = p.split()
            mod = parts[0] if parts[0] in ("out", "ref", "in") else ""
            params.append((mod, parts[-2], parts[-1]))
        externs[m.group("name")] = (m.group("ret"), params)
    return externs


def needs_adapter(params) -> bool:
    return any(t == "StringBuilder" or t.endswith("Delegate") for _, t, _ in params)


def hand_written_adapters() -> set:
    """Adapters implemented in LibRdKafka.Modern.cs (callback trampolines)."""
    text = MODERN.read_text()
    block = text[text.index("class Adapters"):]
    return set(re.findall(r"internal static (?:unsafe )?\S+ (rd_kafka_\w+)\s*\(", block))


def gen_adapter(name, ret, params) -> str:
    """
    Emits an adapter with the upstream wrapper signature that calls the
    source-generated import: StringBuilder buffers become a rented byte
    buffer (null passes through as a null pointer, as librdkafka expects for
    size queries), delegates become function pointers.
    """
    sig = ", ".join(f"{m + ' ' if m else ''}{t} {n}" for m, t, n in params)
    args = []
    sb = None
    for i, (m, t, n) in enumerate(params):
        if t == "StringBuilder":
            if sb is not None:
                sys.exit(f"{name}: more than one StringBuilder parameter is not supported")
            sb = (n, params[i + 1][2])  # buffer, its size (the following parameter)
            args.append(f"p_{n}")
        elif t.endswith("Delegate"):
            args.append(f"FunctionPointer({n})")
        else:
            args.append(f"{m + ' ' if m else ''}{n}")
    call = f"NM.{name}({', '.join(args)})"
    ret_kw = "" if ret == "void" else "return "
    head = f"            internal static {ret} {name}({sig})"
    if sb is None:
        return f"{head}\n                => {call};\n"
    buf, size = sb
    return f"""{head}
            {{
                var buffer = {buf} == null ? null : RentErrStr({size});
                try
                {{
                    fixed (byte* p_{buf} = buffer)
                    {{
                        {ret_kw}{call};
                    }}
                }}
                finally
                {{
                    if (buffer != null) {{ ReturnErrStr(buffer, {buf}); }}
                }}
            }}
"""


def gen_set_delegates() -> None:
    externs = parse_externs()
    hand_written = hand_written_adapters()
    text = LIB_SRC.read_text()
    m = re.search(r"static bool SetDelegates\(Type nativeMethodsClass\)\n\s*\{(.*?)\n        \}\n", text, flags=re.S)
    if not m:
        sys.exit("SetDelegates(Type) not found in LibRdKafka.cs")
    # Line comments would otherwise glue onto the following statement.
    body = re.sub(r"//[^\n]*", "", m.group(1))

    # Statements may span several lines upstream; match on the ';' separated
    # statement with whitespace collapsed, keeping blank-line grouping.
    stmt_re = re.compile(
        r'^(?P<field>_\w+) = \((?P<type>.+?)\)methods\.Single\(m => m\.Name == "(?P<native>\w+)"\)'
        r"\.CreateDelegate\(typeof\s*\(.+\)\);$"
    )
    expected = body.count("methods.Single(")
    out = []
    generated = []
    bound = 0
    for chunk in re.split(r"\n\s*\n", body):
        for stmt in chunk.split(";"):
            stmt = " ".join(stmt.split())
            if not stmt:
                continue
            lm = stmt_re.match(stmt + ";")
            if not lm:
                continue  # the `methods` local and the probe block; regenerated below
            bound += 1
            field, native = lm.group("field"), lm.group("native")
            if native not in externs:
                sys.exit(f"{native} is bound in LibRdKafka.cs but not declared in NativeMethods.cs")
            ret, params = externs[native]
            if needs_adapter(params):
                out.append(f"            {field} = Adapters.{native};")
                if native not in hand_written:
                    generated.append(gen_adapter(native, ret, params))
            else:
                out.append(f"            {field} = NM.{native};")
        out.append("")

    if bound != expected:
        sys.exit(f"parsed {bound} bindings but LibRdKafka.cs has {expected}; fix stmt_re")

    content = GENERATED_BANNER.format(src=LIB_SRC.name) + """#if NET8_0_OR_GREATER
using System;
using System.Text;
using Confluent.Kafka.Admin;
using NM = Confluent.Kafka.Impl.NativeMethods.NativeMethods;


namespace Confluent.Kafka.Impl
{
    internal static partial class Librdkafka
    {
        /// <summary>
        ///     Reflection-free counterpart of SetDelegates(Type): binds every
        ///     delegate field to the source-generated P/Invoke of the same name
        ///     (or to an adapter when the upstream signature is not expressible
        ///     as a source-generated P/Invoke).
        /// </summary>
        static unsafe bool SetDelegates()
        {
""" + "\n".join(out).rstrip() + """

            try
            {
                // throws if the native library failed to load.
                _err2str(ErrorCode.NoError);
            }
            catch (Exception)
            {
                return false;
            }

            return true;
        }

        /// <summary>
        ///     Generated adapters (see LibRdKafka.Modern.cs for the hand written
        ///     ones, which take precedence). Cold paths only.
        /// </summary>
        private static unsafe partial class Adapters
        {
""" + "\n".join(generated).rstrip() + """
        }
    }
}
#endif
"""
    LIB_DST.write_text(content)
    print(f"bound {bound} functions; {len(generated)} generated adapters, "
          f"{len(hand_written)} hand written: {', '.join(sorted(hand_written))}")


if __name__ == "__main__":
    gen_native_methods()
    gen_set_delegates()
    print(f"wrote {NATIVE_DST.relative_to(ROOT.parent.parent)}")
    print(f"wrote {LIB_DST.relative_to(ROOT.parent.parent)}")
