// <auto-generated>
//     Generated by scripts/gen-aot-bindings.py from LibRdKafka.cs.
//     Do not edit by hand - re-run the script after syncing with upstream.
// </auto-generated>
#if NET8_0_OR_GREATER
using System;
using System.Text;
using Confluent.Kafka.Admin;
using NM = Confluent.Kafka.Impl.NativeMethods.NativeMethods;


namespace Confluent.Kafka.Impl
{
    internal static partial class Librdkafka
    {
        /// <summary>
        ///     Reflection-free counterpart of SetDelegates(Type): binds every
        ///     delegate field to the source-generated P/Invoke of the same name
        ///     (or to an adapter when the upstream signature is not expressible
        ///     as a source-generated P/Invoke).
        /// </summary>
        static unsafe bool SetDelegates()
        {

            _version = NM.rd_kafka_version;
            _version_str = NM.rd_kafka_version_str;
            _get_debug_contexts = NM.rd_kafka_get_debug_contexts;
            _err2str = NM.rd_kafka_err2str;
            _last_error = NM.rd_kafka_last_error;
            _fatal_error = Adapters.rd_kafka_fatal_error;
            _message_errstr = NM.rd_kafka_message_errstr;
            _topic_partition_list_new = NM.rd_kafka_topic_partition_list_new;
            _topic_partition_list_destroy = NM.rd_kafka_topic_partition_list_destroy;
            _topic_partition_list_add = NM.rd_kafka_topic_partition_list_add;
            _headers_new = NM.rd_kafka_headers_new;
            _headers_destroy = NM.rd_kafka_headers_destroy;
            _header_add = NM.rd_kafka_header_add;
            _header_get_all = NM.rd_kafka_header_get_all;
            _message_timestamp = NM.rd_kafka_message_timestamp;
            _message_headers = NM.rd_kafka_message_headers;
            _message_status = NM.rd_kafka_message_status;
            _message_leader_epoch = NM.rd_kafka_message_leader_epoch;
            _message_destroy = NM.rd_kafka_message_destroy;
            _conf_new = NM.rd_kafka_conf_new;
            _conf_destroy = NM.rd_kafka_conf_destroy;
            _conf_dup = NM.rd_kafka_conf_dup;
            _conf_set = Adapters.rd_kafka_conf_set;
            _conf_set_dr_msg_cb = Adapters.rd_kafka_conf_set_dr_msg_cb;
            _conf_set_rebalance_cb = Adapters.rd_kafka_conf_set_rebalance_cb;
            _conf_set_error_cb = Adapters.rd_kafka_conf_set_error_cb;
            _conf_set_offset_commit_cb = Adapters.rd_kafka_conf_set_offset_commit_cb;
            _conf_set_log_cb = Adapters.rd_kafka_conf_set_log_cb;
            _conf_set_stats_cb = Adapters.rd_kafka_conf_set_stats_cb;
            _conf_set_oauthbearer_token_refresh_cb = Adapters.rd_kafka_conf_set_oauthbearer_token_refresh_cb;
            _oauthbearer_set_token = Adapters.rd_kafka_oauthbearer_set_token;
            _oauthbearer_set_token_failure = NM.rd_kafka_oauthbearer_set_token_failure;
            _conf_set_default_topic_conf = NM.rd_kafka_conf_set_default_topic_conf;
            _conf_get_default_topic_conf = NM.rd_kafka_conf_get_default_topic_conf;
            _conf_get = Adapters.rd_kafka_conf_get;
            _topic_conf_get = Adapters.rd_kafka_topic_conf_get;
            _conf_dump = NM.rd_kafka_conf_dump;
            _topic_conf_dump = NM.rd_kafka_topic_conf_dump;
            _conf_dump_free = NM.rd_kafka_conf_dump_free;
            _topic_conf_new = NM.rd_kafka_topic_conf_new;
            _topic_conf_dup = NM.rd_kafka_topic_conf_dup;
            _default_topic_conf_dup = NM.rd_kafka_default_topic_conf_dup;
            _topic_conf_destroy = NM.rd_kafka_topic_conf_destroy;
            _topic_conf_set = Adapters.rd_kafka_topic_conf_set;
            _topic_conf_set_partitioner_cb = Adapters.rd_kafka_topic_conf_set_partitioner_cb;
            _topic_conf_set_opaque = NM.rd_kafka_topic_conf_set_opaque;
            _topic_partition_available = NM.rd_kafka_topic_partition_available;
            _topic_partition_get_leader_epoch = NM.rd_kafka_topic_partition_get_leader_epoch;
            _topic_partition_set_leader_epoch = NM.rd_kafka_topic_partition_set_leader_epoch;
            _init_transactions = NM.rd_kafka_init_transactions;
            _begin_transaction = NM.rd_kafka_begin_transaction;
            _commit_transaction = NM.rd_kafka_commit_transaction;
            _abort_transaction = NM.rd_kafka_abort_transaction;
            _send_offsets_to_transaction = NM.rd_kafka_send_offsets_to_transaction;
            _rd_kafka_consumer_group_metadata = NM.rd_kafka_consumer_group_metadata;
            _rd_kafka_consumer_group_metadata_destroy = NM.rd_kafka_consumer_group_metadata_destroy;
            _rd_kafka_consumer_group_metadata_write = NM.rd_kafka_consumer_group_metadata_write;
            _rd_kafka_consumer_group_metadata_read = NM.rd_kafka_consumer_group_metadata_read;
            _new = Adapters.rd_kafka_new;
            _name = NM.rd_kafka_name;
            _memberid = NM.rd_kafka_memberid;
            _Uuid_new = NM.rd_kafka_Uuid_new;
            _Uuid_base64str = NM.rd_kafka_Uuid_base64str;
            _Uuid_most_significant_bits = NM.rd_kafka_Uuid_most_significant_bits;
            _Uuid_least_significant_bits = NM.rd_kafka_Uuid_least_significant_bits;
            _Uuid_destroy = NM.rd_kafka_Uuid_destroy;
            _topic_new = NM.rd_kafka_topic_new;
            _topic_destroy = NM.rd_kafka_topic_destroy;
            _topic_name = NM.rd_kafka_topic_name;
            _poll = NM.rd_kafka_poll;
            _poll_set_consumer = NM.rd_kafka_poll_set_consumer;
            _query_watermark_offsets = NM.rd_kafka_query_watermark_offsets;
            _get_watermark_offsets = NM.rd_kafka_get_watermark_offsets;
            _offsets_for_times = NM.rd_kafka_offsets_for_times;
            _mem_free = NM.rd_kafka_mem_free;
            _subscribe = NM.rd_kafka_subscribe;
            _unsubscribe = NM.rd_kafka_unsubscribe;
            _subscription = NM.rd_kafka_subscription;
            _consumer_poll = NM.rd_kafka_consumer_poll;
            _consumer_close = NM.rd_kafka_consumer_close;
            _assign = NM.rd_kafka_assign;
            _incremental_assign = NM.rd_kafka_incremental_assign;
            _incremental_unassign = NM.rd_kafka_incremental_unassign;
            _assignment_lost = NM.rd_kafka_assignment_lost;
            _rebalance_protocol = NM.rd_kafka_rebalance_protocol;
            _assignment = NM.rd_kafka_assignment;
            _offsets_store = NM.rd_kafka_offsets_store;
            _commit = NM.rd_kafka_commit;
            _commit_queue = Adapters.rd_kafka_commit_queue;
            _committed = NM.rd_kafka_committed;
            _pause_partitions = NM.rd_kafka_pause_partitions;
            _resume_partitions = NM.rd_kafka_resume_partitions;
            _seek = NM.rd_kafka_seek;
            _seek_partitions = NM.rd_kafka_seek_partitions;
            _position = NM.rd_kafka_position;
            _produceva = NM.rd_kafka_produceva;
            _flush = NM.rd_kafka_flush;
            _metadata = NM.rd_kafka_metadata;
            _metadata_destroy = NM.rd_kafka_metadata_destroy;
            _list_groups = NM.rd_kafka_list_groups;
            _group_list_destroy = NM.rd_kafka_group_list_destroy;
            _brokers_add = NM.rd_kafka_brokers_add;
            _sasl_set_credentials = NM.rd_kafka_sasl_set_credentials;
            _outq_len = NM.rd_kafka_outq_len;
            _queue_new = NM.rd_kafka_queue_new;
            _queue_destroy = NM.rd_kafka_queue_destroy;
            _event_opaque = NM.rd_kafka_event_opaque;
            _event_type = NM.rd_kafka_event_type;
            _event_error = NM.rd_kafka_event_error;
            _event_error_string = NM.rd_kafka_event_error_string;
            _event_topic_partition_list = NM.rd_kafka_event_topic_partition_list;
            _event_destroy = NM.rd_kafka_event_destroy;
            _queue_poll = NM.rd_kafka_queue_poll;

            _AdminOptions_new = NM.rd_kafka_AdminOptions_new;
            _AdminOptions_destroy = NM.rd_kafka_AdminOptions_destroy;
            _AdminOptions_set_request_timeout = Adapters.rd_kafka_AdminOptions_set_request_timeout;
            _AdminOptions_set_operation_timeout = Adapters.rd_kafka_AdminOptions_set_operation_timeout;
            _AdminOptions_set_validate_only = Adapters.rd_kafka_AdminOptions_set_validate_only;
            _AdminOptions_set_incremental = Adapters.rd_kafka_AdminOptions_set_incremental;
            _AdminOptions_set_broker = Adapters.rd_kafka_AdminOptions_set_broker;
            _AdminOptions_set_opaque = NM.rd_kafka_AdminOptions_set_opaque;
            _AdminOptions_set_require_stable_offsets = NM.rd_kafka_AdminOptions_set_require_stable_offsets;
            _AdminOptions_set_include_authorized_operations = NM.rd_kafka_AdminOptions_set_include_authorized_operations;
            _AdminOptions_set_match_consumer_group_states = NM.rd_kafka_AdminOptions_set_match_consumer_group_states;
            _AdminOptions_set_match_consumer_group_types = NM.rd_kafka_AdminOptions_set_match_consumer_group_types;
            _AdminOptions_set_isolation_level = NM.rd_kafka_AdminOptions_set_isolation_level;

            _NewTopic_new = Adapters.rd_kafka_NewTopic_new;
            _NewTopic_destroy = NM.rd_kafka_NewTopic_destroy;

            _NewTopic_set_replica_assignment = Adapters.rd_kafka_NewTopic_set_replica_assignment;
            _NewTopic_set_config = NM.rd_kafka_NewTopic_set_config;

            _CreateTopics = NM.rd_kafka_CreateTopics;
            _CreateTopics_result_topics = NM.rd_kafka_CreateTopics_result_topics;

            _DeleteTopic_new = NM.rd_kafka_DeleteTopic_new;
            _DeleteTopic_destroy = NM.rd_kafka_DeleteTopic_destroy;

            _DeleteTopics = NM.rd_kafka_DeleteTopics;
            _DeleteTopics_result_topics = NM.rd_kafka_DeleteTopics_result_topics;

            _DeleteGroup_new = NM.rd_kafka_DeleteGroup_new;
            _DeleteGroup_destroy = NM.rd_kafka_DeleteGroup_destroy;

            _DeleteGroups = NM.rd_kafka_DeleteGroups;
            _DeleteGroups_result_groups = NM.rd_kafka_DeleteGroups_result_groups;

            _DeleteRecords_new = NM.rd_kafka_DeleteRecords_new;
            _DeleteRecords_destroy = NM.rd_kafka_DeleteRecords_destroy;

            _DeleteRecords = NM.rd_kafka_DeleteRecords;
            _DeleteRecords_result_offsets = NM.rd_kafka_DeleteRecords_result_offsets;

            _DeleteConsumerGroupOffsets_new = NM.rd_kafka_DeleteConsumerGroupOffsets_new;
            _DeleteConsumerGroupOffsets_destroy = NM.rd_kafka_DeleteConsumerGroupOffsets_destroy;

            _DeleteConsumerGroupOffsets = NM.rd_kafka_DeleteConsumerGroupOffsets;
            _DeleteConsumerGroupOffsets_result_groups = NM.rd_kafka_DeleteConsumerGroupOffsets_result_groups;

            _NewPartitions_new = Adapters.rd_kafka_NewPartitions_new;
            _NewPartitions_destroy = NM.rd_kafka_NewPartitions_destroy;
            _NewPartitions_set_replica_assignment = Adapters.rd_kafka_NewPartitions_set_replica_assignment;

            _CreatePartitions = NM.rd_kafka_CreatePartitions;
            _CreatePartitions_result_topics = NM.rd_kafka_CreatePartitions_result_topics;

            _ConfigSource_name = NM.rd_kafka_ConfigSource_name;
            _ConfigEntry_name = NM.rd_kafka_ConfigEntry_name;
            _ConfigEntry_value = NM.rd_kafka_ConfigEntry_value;
            _ConfigEntry_source = NM.rd_kafka_ConfigEntry_source;
            _ConfigEntry_is_read_only = NM.rd_kafka_ConfigEntry_is_read_only;
            _ConfigEntry_is_default = NM.rd_kafka_ConfigEntry_is_default;
            _ConfigEntry_is_sensitive = NM.rd_kafka_ConfigEntry_is_sensitive;
            _ConfigEntry_is_synonym = NM.rd_kafka_ConfigEntry_is_synonym;
            _ConfigEntry_synonyms = NM.rd_kafka_ConfigEntry_synonyms;

            _ResourceType_name = NM.rd_kafka_ResourceType_name;

            _ConfigResource_new = NM.rd_kafka_ConfigResource_new;
            _ConfigResource_destroy = NM.rd_kafka_ConfigResource_destroy;
            _ConfigResource_add_config = NM.rd_kafka_ConfigResource_add_config;
            _ConfigResource_set_config = NM.rd_kafka_ConfigResource_set_config;
            _ConfigResource_delete_config = NM.rd_kafka_ConfigResource_delete_config;
            _ConfigResource_add_incremental_config = NM.rd_kafka_ConfigResource_add_incremental_config;
            _ConfigResource_configs = NM.rd_kafka_ConfigResource_configs;

            _ConfigResource_type = NM.rd_kafka_ConfigResource_type;
            _ConfigResource_name = NM.rd_kafka_ConfigResource_name;
            _ConfigResource_error = NM.rd_kafka_ConfigResource_error;
            _ConfigResource_error_string = NM.rd_kafka_ConfigResource_error_string;

            _AlterConfigs = NM.rd_kafka_AlterConfigs;
            _AlterConfigs_result_resources = NM.rd_kafka_AlterConfigs_result_resources;

            _IncrementalAlterConfigs = NM.rd_kafka_IncrementalAlterConfigs;
            _IncrementalAlterConfigs_result_resources = NM.rd_kafka_IncrementalAlterConfigs_result_resources;

            _DescribeConfigs = NM.rd_kafka_DescribeConfigs;
            _DescribeConfigs_result_resources = NM.rd_kafka_DescribeConfigs_result_resources;

            _AclBinding_new = Adapters.rd_kafka_AclBinding_new;
            _AclBindingFilter_new = Adapters.rd_kafka_AclBindingFilter_new;
            _AclBinding_destroy = NM.rd_kafka_AclBinding_destroy;
            _AclBinding_restype = NM.rd_kafka_AclBinding_restype;
            _AclBinding_name = NM.rd_kafka_AclBinding_name;
            _AclBinding_resource_pattern_type = NM.rd_kafka_AclBinding_resource_pattern_type;
            _AclBinding_principal = NM.rd_kafka_AclBinding_principal;
            _AclBinding_host = NM.rd_kafka_AclBinding_host;
            _AclBinding_operation = NM.rd_kafka_AclBinding_operation;
            _AclBinding_permission_type = NM.rd_kafka_AclBinding_permission_type;
            _CreateAcls = NM.rd_kafka_CreateAcls;
            _CreateAcls_result_acls = NM.rd_kafka_CreateAcls_result_acls;
            _acl_result_error = NM.rd_kafka_acl_result_error;
            _DescribeAcls = NM.rd_kafka_DescribeAcls;
            _DescribeAcls_result_acls = NM.rd_kafka_DescribeAcls_result_acls;
            _DeleteAcls = NM.rd_kafka_DeleteAcls;
            _DeleteAcls_result_responses = NM.rd_kafka_DeleteAcls_result_responses;
            _DeleteAcls_result_response_error = NM.rd_kafka_DeleteAcls_result_response_error;
            _DeleteAcls_result_response_matching_acls = NM.rd_kafka_DeleteAcls_result_response_matching_acls;

            _AlterConsumerGroupOffsets_new = NM.rd_kafka_AlterConsumerGroupOffsets_new;
            _AlterConsumerGroupOffsets_destroy = NM.rd_kafka_AlterConsumerGroupOffsets_destroy;
            _AlterConsumerGroupOffsets_result_groups = NM.rd_kafka_AlterConsumerGroupOffsets_result_groups;
            _AlterConsumerGroupOffsets = NM.rd_kafka_AlterConsumerGroupOffsets;

            _ListConsumerGroupOffsets_new = NM.rd_kafka_ListConsumerGroupOffsets_new;
            _ListConsumerGroupOffsets_destroy = NM.rd_kafka_ListConsumerGroupOffsets_destroy;
            _ListConsumerGroupOffsets_result_groups = NM.rd_kafka_ListConsumerGroupOffsets_result_groups;
            _ListConsumerGroupOffsets = NM.rd_kafka_ListConsumerGroupOffsets;

            _ListConsumerGroups = NM.rd_kafka_ListConsumerGroups;
            _ConsumerGroupListing_group_id = NM.rd_kafka_ConsumerGroupListing_group_id;
            _ConsumerGroupListing_is_simple_consumer_group = NM.rd_kafka_ConsumerGroupListing_is_simple_consumer_group;
            _ConsumerGroupListing_state = NM.rd_kafka_ConsumerGroupListing_state;
            _ConsumerGroupListing_type = NM.rd_kafka_ConsumerGroupListing_type;
            _ListConsumerGroups_result_valid = NM.rd_kafka_ListConsumerGroups_result_valid;
            _ListConsumerGroups_result_errors = NM.rd_kafka_ListConsumerGroups_result_errors;

            _DescribeConsumerGroups = NM.rd_kafka_DescribeConsumerGroups;
            _DescribeConsumerGroups_result_groups = NM.rd_kafka_DescribeConsumerGroups_result_groups;
            _ConsumerGroupDescription_group_id = NM.rd_kafka_ConsumerGroupDescription_group_id;
            _ConsumerGroupDescription_error = NM.rd_kafka_ConsumerGroupDescription_error;
            _ConsumerGroupDescription_is_simple_consumer_group = NM.rd_kafka_ConsumerGroupDescription_is_simple_consumer_group;
            _ConsumerGroupDescription_partition_assignor = NM.rd_kafka_ConsumerGroupDescription_partition_assignor;
            _ConsumerGroupDescription_state = NM.rd_kafka_ConsumerGroupDescription_state;
            _ConsumerGroupDescription_type = NM.rd_kafka_ConsumerGroupDescription_type;
            _ConsumerGroupDescription_coordinator = NM.rd_kafka_ConsumerGroupDescription_coordinator;
            _ConsumerGroupDescription_member_count = NM.rd_kafka_ConsumerGroupDescription_member_count;
            _ConsumerGroupDescription_authorized_operations = NM.rd_kafka_ConsumerGroupDescription_authorized_operations;
            _ConsumerGroupDescription_member = NM.rd_kafka_ConsumerGroupDescription_member;
            _MemberDescription_client_id = NM.rd_kafka_MemberDescription_client_id;
            _MemberDescription_group_instance_id = NM.rd_kafka_MemberDescription_group_instance_id;
            _MemberDescription_consumer_id = NM.rd_kafka_MemberDescription_consumer_id;
            _MemberDescription_host = NM.rd_kafka_MemberDescription_host;
            _MemberDescription_assignment = NM.rd_kafka_MemberDescription_assignment;
            _MemberAssignment_partitions = NM.rd_kafka_MemberAssignment_partitions;
            _MemberDescription_target_assignment = NM.rd_kafka_MemberDescription_target_assignment;
            _Node_id = NM.rd_kafka_Node_id;
            _Node_host = NM.rd_kafka_Node_host;
            _Node_port = NM.rd_kafka_Node_port;
            _Node_rack = NM.rd_kafka_Node_rack;

            _DescribeUserScramCredentials = NM.rd_kafka_DescribeUserScramCredentials;
            _DescribeUserScramCredentials_result_descriptions = NM.rd_kafka_DescribeUserScramCredentials_result_descriptions;
            _UserScramCredentialsDescription_user = NM.rd_kafka_UserScramCredentialsDescription_user;
            _UserScramCredentialsDescription_error = NM.rd_kafka_UserScramCredentialsDescription_error;
            _UserScramCredentialsDescription_scramcredentialinfo_count = NM.rd_kafka_UserScramCredentialsDescription_scramcredentialinfo_count;
            _UserScramCredentialsDescription_scramcredentialinfo = NM.rd_kafka_UserScramCredentialsDescription_scramcredentialinfo;
            _ScramCredentialInfo_mechanism = NM.rd_kafka_ScramCredentialInfo_mechanism;
            _ScramCredentialInfo_iterations = NM.rd_kafka_ScramCredentialInfo_iterations;

            _UserScramCredentialUpsertion_new = NM.rd_kafka_UserScramCredentialUpsertion_new;
            _UserScramCredentialDeletion_new = NM.rd_kafka_UserScramCredentialDeletion_new;
            _UserScramCredentialAlteration_destroy = NM.rd_kafka_UserScramCredentialAlteration_destroy;
            _AlterUserScramCredentials = NM.rd_kafka_AlterUserScramCredentials;
            _AlterUserScramCredentials_result_responses = NM.rd_kafka_AlterUserScramCredentials_result_responses;
            _AlterUserScramCredentials_result_response_user = NM.rd_kafka_AlterUserScramCredentials_result_response_user;
            _AlterUserScramCredentials_result_response_error = NM.rd_kafka_AlterUserScramCredentials_result_response_error;

            _ListOffsets = NM.rd_kafka_ListOffsets;
            _ListOffsets_result_infos = NM.rd_kafka_ListOffsets_result_infos;
            _ListOffsetsResultInfo_timestamp = NM.rd_kafka_ListOffsetsResultInfo_timestamp;
            _ListOffsetsResultInfo_topic_partition = NM.rd_kafka_ListOffsetsResultInfo_topic_partition;

            _DescribeTopics = NM.rd_kafka_DescribeTopics;
            _DescribeTopics_result_topics = NM.rd_kafka_DescribeTopics_result_topics;
            _TopicCollection_of_topic_names = NM.rd_kafka_TopicCollection_of_topic_names;
            _TopicCollection_destroy = NM.rd_kafka_TopicCollection_destroy;
            _TopicDescription_error = NM.rd_kafka_TopicDescription_error;
            _TopicDescription_name = NM.rd_kafka_TopicDescription_name;
            _TopicDescription_topic_id = NM.rd_kafka_TopicDescription_topic_id;
            _TopicDescription_partitions = NM.rd_kafka_TopicDescription_partitions;
            _TopicDescription_is_internal = NM.rd_kafka_TopicDescription_is_internal;
            _TopicDescription_authorized_operations = NM.rd_kafka_TopicDescription_authorized_operations;
            _TopicPartitionInfo_isr = NM.rd_kafka_TopicPartitionInfo_isr;
            _TopicPartitionInfo_leader = NM.rd_kafka_TopicPartitionInfo_leader;
            _TopicPartitionInfo_partition = NM.rd_kafka_TopicPartitionInfo_partition;
            _TopicPartitionInfo_replicas = NM.rd_kafka_TopicPartitionInfo_replicas;

            _ElectLeadersRequest_new = NM.rd_kafka_ElectLeaders_new;
            _ElectLeadersRequest_destroy = NM.rd_kafka_ElectLeaders_destroy;
            _ElectLeaders = NM.rd_kafka_ElectLeaders;
            _ElectLeaders_result_partitions = NM.rd_kafka_ElectLeaders_result_partitions;
            _TopicPartitionResult_partition = NM.rd_kafka_topic_partition_result_partition;
            _TopicPartitionResult_error = NM.rd_kafka_topic_partition_result_error;

            _DescribeCluster = NM.rd_kafka_DescribeCluster;
            _DescribeCluster_result_nodes = NM.rd_kafka_DescribeCluster_result_nodes;
            _DescribeCluster_result_authorized_operations = NM.rd_kafka_DescribeCluster_result_authorized_operations;
            _DescribeCluster_result_controller = NM.rd_kafka_DescribeCluster_result_controller;
            _DescribeCluster_result_cluster_id = NM.rd_kafka_DescribeCluster_result_cluster_id;

            _topic_result_error = NM.rd_kafka_topic_result_error;
            _topic_result_error_string = NM.rd_kafka_topic_result_error_string;
            _topic_result_name = NM.rd_kafka_topic_result_name;

            _group_result_name = NM.rd_kafka_group_result_name;
            _group_result_error = NM.rd_kafka_group_result_error;
            _group_result_partitions = NM.rd_kafka_group_result_partitions;

            _destroy = NM.rd_kafka_destroy;
            _destroy_flags = NM.rd_kafka_destroy_flags;

            _error_code = NM.rd_kafka_error_code;
            _error_string = NM.rd_kafka_error_string;
            _error_is_fatal = NM.rd_kafka_error_is_fatal;
            _error_is_retriable = NM.rd_kafka_error_is_retriable;
            _error_txn_requires_abort = NM.rd_kafka_error_txn_requires_abort;
            _error_destroy = NM.rd_kafka_error_destroy;

            try
            {
                // throws if the native library failed to load.
                _err2str(ErrorCode.NoError);
            }
            catch (Exception)
            {
                return false;
            }

            return true;
        }

        /// <summary>
        ///     Generated adapters (see LibRdKafka.Modern.cs for the hand written
        ///     ones, which take precedence). Cold paths only.
        /// </summary>
        private static unsafe partial class Adapters
        {
            internal static ErrorCode rd_kafka_fatal_error(IntPtr rk, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_fatal_error(rk, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ConfRes rd_kafka_conf_set(IntPtr conf, string name, string value, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_conf_set(conf, name, value, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_oauthbearer_set_token(IntPtr rk, string token_value, long md_lifetime_ms, string md_principal_name, string[] extensions, UIntPtr extension_size, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_oauthbearer_set_token(rk, token_value, md_lifetime_ms, md_principal_name, extensions, extension_size, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ConfRes rd_kafka_conf_get(IntPtr conf, string name, StringBuilder dest, ref UIntPtr dest_size)
            {
                var buffer = dest == null ? null : RentErrStr(dest_size);
                try
                {
                    fixed (byte* p_dest = buffer)
                    {
                        return NM.rd_kafka_conf_get(conf, name, p_dest, ref dest_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, dest); }
                }
            }

            internal static ConfRes rd_kafka_topic_conf_get(IntPtr conf, string name, StringBuilder dest, ref UIntPtr dest_size)
            {
                var buffer = dest == null ? null : RentErrStr(dest_size);
                try
                {
                    fixed (byte* p_dest = buffer)
                    {
                        return NM.rd_kafka_topic_conf_get(conf, name, p_dest, ref dest_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, dest); }
                }
            }

            internal static ConfRes rd_kafka_topic_conf_set(IntPtr conf, string name, string value, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_topic_conf_set(conf, name, value, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static SafeKafkaHandle rd_kafka_new(RdKafkaType type, IntPtr conf, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_new(type, conf, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_commit_queue(IntPtr rk, IntPtr offsets, IntPtr rkqu, Librdkafka.CommitDelegate cb, IntPtr opaque)
                => NM.rd_kafka_commit_queue(rk, offsets, rkqu, FunctionPointer(cb), opaque);

            internal static ErrorCode rd_kafka_AdminOptions_set_request_timeout(IntPtr options, IntPtr timeout_ms, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AdminOptions_set_request_timeout(options, timeout_ms, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_AdminOptions_set_operation_timeout(IntPtr options, IntPtr timeout_ms, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AdminOptions_set_operation_timeout(options, timeout_ms, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_AdminOptions_set_validate_only(IntPtr options, IntPtr true_or_false, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AdminOptions_set_validate_only(options, true_or_false, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_AdminOptions_set_incremental(IntPtr options, IntPtr true_or_false, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AdminOptions_set_incremental(options, true_or_false, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_AdminOptions_set_broker(IntPtr options, int broker_id, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AdminOptions_set_broker(options, broker_id, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static IntPtr rd_kafka_NewTopic_new(string topic, IntPtr num_partitions, IntPtr replication_factor, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_NewTopic_new(topic, num_partitions, replication_factor, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_NewTopic_set_replica_assignment(IntPtr new_topic, int partition, int[] broker_ids, UIntPtr broker_id_cnt, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_NewTopic_set_replica_assignment(new_topic, partition, broker_ids, broker_id_cnt, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static IntPtr rd_kafka_NewPartitions_new(string topic, UIntPtr new_total_cnt, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_NewPartitions_new(topic, new_total_cnt, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static ErrorCode rd_kafka_NewPartitions_set_replica_assignment(IntPtr new_parts, int new_partition_idx, int[] broker_ids, UIntPtr broker_id_cnt, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_NewPartitions_set_replica_assignment(new_parts, new_partition_idx, broker_ids, broker_id_cnt, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static IntPtr rd_kafka_AclBinding_new(ResourceType restype, string name, ResourcePatternType resource_pattern_type, string principal, string host, AclOperation operation, AclPermissionType permission_type, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AclBinding_new(restype, name, resource_pattern_type, principal, host, operation, permission_type, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }

            internal static IntPtr rd_kafka_AclBindingFilter_new(ResourceType restype, string name, ResourcePatternType resource_pattern_type, string principal, string host, AclOperation operation, AclPermissionType permission_type, StringBuilder errstr, UIntPtr errstr_size)
            {
                var buffer = errstr == null ? null : RentErrStr(errstr_size);
                try
                {
                    fixed (byte* p_errstr = buffer)
                    {
                        return NM.rd_kafka_AclBindingFilter_new(restype, name, resource_pattern_type, principal, host, operation, permission_type, p_errstr, errstr_size);
                    }
                }
                finally
                {
                    if (buffer != null) { ReturnErrStr(buffer, errstr); }
                }
            }
        }
    }
}
#endif
